version: ~> 1.0
dist: bionic
language: node_js
install:
  - npm ci
script:
  # Test Git hooks in CI, to make sure script upgrades do not break them.
  - npm run prepare
  - ./.git/hooks/pre-commit
  - git log -1 --pretty=%B >> latest.log && ./.git/hooks/commit-msg latest.log
  - npm run test:ci
  - npx commitlint-travis
branches:
  except:
    - gh-pages
notifications:
  email: false
